token:
  secret: my-secret-key-1234567890-from-github-repository-ecommerce-#4
  expiration-time: 864000000

gateway:
  ip: 10.20.30.40

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password: '{cipher}AYAYxJ2dUhlELhKXPnnWJ6PmfxWXjy+aZ3CviFCnCQfRpo6w2guk0yzCf9A0M5rgpI8piNWnc+Rfhm1mVkRNWQguzo4fYp0fYoyeiRY6GnLt9usvRRxPHTEjmxqtQ6Hd9m8BXmI2c+UxScSS8en605gsR+nafpKoBECQavDYL92kj6X82BDoDv+8sLJNWia6E3BSr0Wkz/Bft/7X7xs4JEH0w2IvIWho9//qKV1xN80AhqQNaxToD7VmclqrtKDrL61layNws/uM3yt27/f0TmrVimOVdaEEQyR2gSi/Rg/MKjyW5Z38R/zLPH48KdACZn8iCCwcdc8e6nG3+xKsKijhcG7uvIMRV7V8VzxqPe1T7ejdIHzg2/M5cGg+Ljv8PyKbd8qvF8wCzoLSZDV9LfT+z6WaRJnGdUWOZZ6BKzA7nfCx5B+GDMOT2zkw2qABWnG/rpGZvYMU5qxoLyLSgHNmnf+MZIsB/tSe++KgED+EXeDu9JuALkH3iixJbQ7Ts3RWqEIK4Fkp5eEp8bhnFBqax/ZVvk+rhUTZaG56AcfegA=='

order-service:
  url: http://order-service/order-service/%s/orders